#Expyriment 0.9.0 (Python 2.7.11), .xpe-file, coding: cp1255
#date: Fri Apr 13 2018 10:43:10
#sha1: b7e963
#modules: grid.py (68c27b), writeToExcel.py (6476cc), nback.py (e10e8f), runStroopTask.py (6656da), stroop.py (6f7be0), runNbackTask.py (615c2a), restBlock.py (9d51ab)
#display: size=(800, 600), window_mode=True, open_gl=2
#os: ('Windows', 'DESKTOP-A6JHBFQ', '10', '10.0.16299', 'AMD64', 'Intel64 Family 6 Model 142 Stepping 9, GenuineIntel')
Time,Type,Event,Value,Detail,Detail2
810,design,log,
#design: #exp: main
#design: block_cnt,block_id,trial_cnt,trial_id
810,design,logged,
810,Experiment,started
829,Stimulus,presented,0
13787,Mouse,received,0-False,wait_event
13788,stderr,received,'Traceback (most recent call last):'
13788,stderr,received,'  File "C:/Users/NOA/fMRI_E_Project/BasicTasks/main.py", line 84, in <module>'
13788,stderr,received,'    str(exp.data._subject), outlet)'
13788,stderr,received,'  File "C:\\Users\\NOA\\fMRI_E_Project\\BasicTasks\\runStroopTask.py", line 57, in __init__'
13788,stderr,received,'    self.experiment = stroop(self.exp, True, self.outlet, self.subNumber)'
13788,stderr,received,'TypeError: __init__() takes exactly 4 arguments (5 given)'
